<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>InfrastructureManager.Application</RootNamespace>
    <AssemblyName>InfrastructureManager.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

</Project>
